// Friet van Desire -- C64 player with synchronised lyrics ticker
//
// Build:    java -jar kickass/KickAss.jar src/player/friet_player.asm
// Run:      x64sc src/player/friet_player.prg
//
// Memory layout:
//   $0801-$080F  BASIC stub (10 SYS 2064)
//   $0810-       Player code + lyrics table
//   $1000-       SID body (loaded straight into place by the PRG)

.const SID_INIT = $1000
.const SID_PLAY = $1003

.var frame_lo = $02
.var frame_hi = $03
.var ly_lo    = $04
.var ly_hi    = $05
.var tmp_len  = $06

// ---- BASIC stub: 10 SYS 2064 ------------------------------------------
*=$0801
    .byte $0B, $08, $0A, $00, $9E
    .text "2064"
    .byte $00, $00, $00

// ---- Player code ------------------------------------------------------
*=$0810
entry:
    sei
    lda #0
    sta frame_lo
    sta frame_hi
    lda #<lyric_table
    sta ly_lo
    lda #>lyric_table
    sta ly_hi

    // Border + background black
    lda #$00
    sta $D020
    sta $D021

    // Clear screen
    lda #$20
    ldx #0
!loop:
    sta $0400,x
    sta $0500,x
    sta $0600,x
    sta $0700,x
    inx
    bne !loop-

    // Set screen colour to light cyan everywhere
    lda #$03
    ldx #0
!loop:
    sta $D800,x
    sta $D900,x
    sta $DA00,x
    sta $DB00,x
    inx
    bne !loop-

    // Header banner at row 1
    ldx #0
!loop:
    lda banner_top,x
    beq !done+
    sta $0400 + 40*1 + 4,x
    inx
    jmp !loop-
!done:

    // Footer credit at row 23
    ldx #0
!loop:
    lda banner_bottom,x
    beq !done+
    sta $0400 + 40*23 + 4,x
    inx
    jmp !loop-
!done:

    // Initialise the SID (subtune 0)
    lda #0
    tax
    tay
    jsr SID_INIT

    // Hook the IRQ vector
    lda #<irq
    sta $0314
    lda #>irq
    sta $0315
    // Disable CIA timer IRQs; switch to VIC raster IRQ
    lda #$7F
    sta $DC0D
    sta $DD0D
    lda $DC0D
    lda $DD0D
    lda #$01
    sta $D01A
    lda #250
    sta $D012
    lda $D011
    and #$7F
    sta $D011
    cli
!forever:
    jmp !forever-

// ---- 50 Hz IRQ: SID play + lyric ticker -------------------------------
irq:
    lda #$FF
    sta $D019
    jsr SID_PLAY
    inc frame_lo
    bne !nh+
    inc frame_hi
!nh:
    jsr maybe_show_lyric
    // Exit via the simple IRQ-return ($EA81 = pull registers + RTI). Do NOT
    // chain to $EA31 — that runs the full KERNAL IRQ which scans keyboard
    // and updates the cursor, both of which clobber our screen RAM writes.
    jmp $EA81

maybe_show_lyric:
    // Sentinel: ($FFFF, *, ...) = end-of-table, stop ticking.
    ldy #0
    lda (ly_lo),y
    cmp #$FF
    bne !nx+
    iny
    lda (ly_lo),y
    cmp #$FF
    bne !nx+
    rts
!nx:
    // Compare ly_lo/ly_hi to (frame_lo, frame_hi)
    ldy #0
    lda (ly_lo),y
    cmp frame_lo
    bne !not_yet+
    iny
    lda (ly_lo),y
    cmp frame_hi
    bne !not_yet+

    // Display row 12: first clear it
    lda #$20
    ldx #39
!clr:
    sta $0400 + 40*12,x
    dex
    bpl !clr-

    // Then copy length bytes of text from after the header
    iny
    lda (ly_lo),y           // y=2, length
    sta tmp_len
    iny                      // y=3, first text byte
    ldx #0
!cp:
    cpx tmp_len
    beq !cp_done+
    lda (ly_lo),y
    sta $0400 + 40*12,x
    iny
    inx
    jmp !cp-
!cp_done:
    // Advance ly_lo/hi by (3 header + tmp_len text)
    clc
    lda ly_lo
    adc tmp_len
    sta ly_lo
    lda ly_hi
    adc #0
    sta ly_hi
    clc
    lda ly_lo
    adc #3
    sta ly_lo
    lda ly_hi
    adc #0
    sta ly_hi
!not_yet:
    rts

// ---- Static banners (screen-code bytes generated by src/build_player.py) --
banner_top:
    .import binary "banner_top.bin"
    .byte 0
banner_bottom:
    .import binary "banner_bottom.bin"
    .byte 0

lyric_table:
    .import binary "lyric_table.bin"
    .byte $FF, $FF, $00       // sentinel

// ---- SID body --------------------------------------------------------
*=$1000
sid_body:
    .import binary "sid_body.bin"
