// Friet met Desire — PURE-AUDIO compo player (X2026 music compo).
//
// No lyric ticker, no beat-strobe — just the SID with a clean static
// credit screen. This is the music-compo entry; the lyric/visual version
// is the separate friet.prg / friet.d64.
//
// Build:  generated by src/build_player.py (compo bins + sid_body.bin)
// Run:    x64sc out/friet_compo.prg   (8580 / PAL)
//
// Memory: $0801 BASIC stub, $0810 player, $1000 SID body.

.const SID_INIT = $1000
.const SID_PLAY = $1003

// ---- BASIC stub: 10 SYS 2064 ------------------------------------------
*=$0801
    .byte $0B, $08, $0A, $00, $9E
    .text "2064"
    .byte $00, $00, $00

// ---- Player code ------------------------------------------------------
*=$0810
entry:
    sei
    // Zero the SID player's ZP work area ($02-$0F) — the play routine
    // expects them at $00 on the first call (see friet.asm note).
    lda #0
    ldx #$0d
!zpclr:
    sta $02,x
    dex
    bpl !zpclr-

    // Lowercase charset
    lda #$17
    sta $D018
    // Border + background black
    lda #$00
    sta $D020
    sta $D021

    // Clear screen to spaces
    lda #$20
    ldx #0
!clr:
    sta $0400,x
    sta $0500,x
    sta $0600,x
    sta $0700,x
    inx
    bne !clr-

    // Screen colour: light grey everywhere
    lda #$0F
    ldx #0
!col:
    sta $D800,x
    sta $D900,x
    sta $DA00,x
    sta $DB00,x
    inx
    bne !col-

    // Three static centred lines (40 screen-codes each) at rows 9/11/13.
    ldx #39
!lines:
    lda compo_title,x
    sta $0400 + 40*9,x
    lda compo_author,x
    sta $0400 + 40*11,x
    lda compo_info,x
    sta $0400 + 40*13,x
    dex
    bpl !lines-

    // Highlight the title row in yellow
    lda #$07
    ldx #39
!ttl:
    sta $D800 + 40*9,x
    dex
    bpl !ttl-

    // Initialise the SID (subtune 0)
    lda #0
    tax
    tay
    jsr SID_INIT

    // Hook the IRQ vector (KERNAL $0314/$0315), VIC raster IRQ
    lda #<irq
    sta $0314
    lda #>irq
    sta $0315
    lda #$7F
    sta $DC0D
    sta $DD0D
    lda $DC0D
    lda $DD0D
    lda #$01
    sta $D01A
    lda #250
    sta $D012
    lda $D011
    and #$7F
    sta $D011
    cli
!forever:
    jmp !forever-

// ---- 50 Hz IRQ: SID play only -----------------------------------------
irq:
    lda #$FF
    sta $D019
    jsr SID_PLAY
    jmp $EA81

// ---- Static credit lines (screen-code bytes from build_player.py) -----
compo_title:
    .import binary "compo_title.bin"
compo_author:
    .import binary "compo_author.bin"
compo_info:
    .import binary "compo_info.bin"

// ---- SID body ---------------------------------------------------------
*=$1000
sid_body:
    .import binary "sid_body.bin"
