#!/usr/bin/env python3
"""Build the stand-alone C64 .prg that plays out/friet.sid with a
synchronised lyrics ticker.

Pipeline:
  1. Extract the raw SID body from out/friet.sid (drop the PSID header
     and the PRG load-address prefix).
  2. Build a binary lyric table from docs/song_layers.yaml, lyric
     lines remapped onto the OUTPUT timeline via the same SEGMENTS
     table compose.py uses.
  3. Drop those binaries plus two banner strings next to
     src/player/friet.asm and invoke KickAssembler.

Output: out/friet.prg (loads at $0801, runs via SYS 2064).
"""
import os, sys, struct, subprocess, yaml

BASE         = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SID_PATH     = os.path.join(BASE, 'out', 'friet.sid')
# Read lyrics from song_layers.yaml (always regenerated by extract_patterns.py)
LAYERS_PATH  = os.path.join(BASE, 'docs', 'song_layers.yaml')
ASM_PATH     = os.path.join(BASE, 'src', 'player', 'friet.asm')
PLAYER_DIR   = os.path.dirname(ASM_PATH)
OUT_PRG      = os.path.join(BASE, 'out', 'friet.prg')
KICKASS_JAR  = os.path.join(BASE, 'kickass', 'KickAss.jar')

# ---- 1. SID body ------------------------------------------------------
with open(SID_PATH, 'rb') as f:
    sid = f.read()
assert sid[:4] == b'PSID', "not a PSID file"
psid_data_offset = struct.unpack('>H', sid[6:8])[0]
psid_load_addr   = struct.unpack('>H', sid[8:10])[0]
sid_init = struct.unpack('>H', sid[10:12])[0]
sid_play = struct.unpack('>H', sid[12:14])[0]
body = sid[psid_data_offset:]
if psid_load_addr == 0:
    sid_load_addr = body[0] | (body[1] << 8)
    sid_code      = body[2:]
else:
    sid_load_addr = psid_load_addr
    sid_code      = body
assert sid_load_addr == 0x1000, f"SID expects $1000 load addr, got ${sid_load_addr:04X}"
print(f"SID load=${sid_load_addr:04X} size={len(sid_code)} bytes "
      f"(init=${sid_init:04X} play=${sid_play:04X})")
with open(os.path.join(PLAYER_DIR, 'sid_body.bin'), 'wb') as f:
    f.write(sid_code)

# ---- 2. Lyrics table --------------------------------------------------
SEGMENTS = [
    (  0.0,  21.5, 'intro'),
    ( 21.5,  54.5, 'verse1'),
    ( 54.5,  88.0, 'prechorus1'),
    ( 88.0, 117.5, 'chorus1'),
    (117.5, 149.5, 'postchorus_nana'),
    (149.5, 153.5, 'breathe1'),
    ( 88.0, 117.5, 'chorus2'),
    (149.5, 153.5, 'breathe2'),
    ( 88.0, 117.5, 'chorus3'),
]
out_offsets = []
cur = 0.0
for s, e, _ in SEGMENTS:
    out_offsets.append(cur)
    cur += e - s

def remap(src_beat):
    for (s, e, _), out_s in zip(SEGMENTS, out_offsets):
        if s <= src_beat < e:
            yield out_s + (src_beat - s)

# ---- Lyrics source: TL-Buis Dutch parody (if available), else karaoke ----
TL_BUIS_PATH = os.path.join(BASE, 'docs', 'tl_buis_lyrics.yaml')

# The standalone .prg embeds the FAST release SID; lyric frames must match
# that tempo. Keep in sync with FAST_BPM in src/compose.py.
FAST_BPM = 175
FRAMES_PER_BEAT = 50.0 * 60 / FAST_BPM   # ≈ 17.14 fr/beat at 175 BPM

if os.path.exists(TL_BUIS_PATH):
    # TL-Buis lyrics: pre-mapped to OUTPUT beats, one text per entry.
    # No syllable grouping needed — each entry is a display line.
    with open(TL_BUIS_PATH) as f:
        tl = yaml.safe_load(f)
    lines = [(l['beat'], l['text']) for l in tl.get('lyrics', [])]
    print(f"Using TL-Buis lyrics: {len(lines)} lines")
else:
    # Fallback: karaoke English syllables from song_layers.yaml
    with open(LAYERS_PATH) as f:
        ly = yaml.safe_load(f)
    syls = [{'beat': l['beat'], 'syllable': l['syllable']}
            for l in ly.get('lyrics', [])]
    LINE_GAP_BEATS = 2.0
    raw_lines = []
    cur_syls, cur_start, last_beat = [], None, None
    for s in syls:
        syl = s['syllable']
        is_line_start = (not syl.startswith(' ')) and syl[:1].isupper()
        big_gap = last_beat is not None and (s['beat'] - last_beat) > LINE_GAP_BEATS
        if (is_line_start or big_gap) and cur_syls:
            raw_lines.append((cur_start, cur_syls))
            cur_syls, cur_start = [], None
        if not cur_syls:
            cur_start = s['beat']
        cur_syls.append(s)
        last_beat = s['beat']
    if cur_syls:
        raw_lines.append((cur_start, cur_syls))
    lines = [(beat, ''.join(s['syllable'] for s in ss).strip())
             for beat, ss in raw_lines]
    print(f"Using karaoke lyrics: {len(lines)} lines")

# Word-wrap any line still > 40 cols. The screen row is 40 cols wide; the
# .asm centres each event by `(40 - len) / 2`, which underflows for >40
# and writes off the bottom of the screen. Emit each wrapped chunk as its
# own event, spaced ~1 beat apart so it has time to read before the next
# line replaces it.
MAX_LINE_COLS = 40
WRAP_BEAT_STEP = 1.0  # beat offset between successive wrapped chunks

def wrap_text(text, width):
    text = text.strip()
    if len(text) <= width:
        return [text]
    chunks, cur = [], ''
    for word in text.split(' '):
        if not cur:
            cur = word[:width]  # single word longer than width: hard-truncate
        elif len(cur) + 1 + len(word) <= width:
            cur += ' ' + word
        else:
            chunks.append(cur)
            cur = word[:width]
    if cur:
        chunks.append(cur)
    return chunks

events = []   # (frame, text)
for line_beat, text in lines:
    chunks = wrap_text(text, MAX_LINE_COLS)
    # TL-Buis lyrics are already in OUTPUT beats; karaoke lyrics need
    # remap(). TL-Buis always has the file, so we just use beat directly.
    for i, chunk in enumerate(chunks):
        events.append((
            int(round((line_beat + i * WRAP_BEAT_STEP) * FRAMES_PER_BEAT)),
            chunk,
        ))
events.sort()
print(f"{len(lines)} lyric lines -> {len(events)} on-screen updates @ {FAST_BPM} BPM")

# ---- Text -> C64 screen codes -----------------------------------------
def to_screen(s, width=40):
    out = []
    for c in s.upper()[:width]:
        o = ord(c)
        if 0x41 <= o <= 0x5A:
            out.append(o - 0x40)            # A-Z -> $01-$1A
        elif o == 0x20:
            out.append(0x20)
        elif 0x30 <= o <= 0x39:
            out.append(o)
        elif o in (44, 46, 33, 39, 47, 45):  # , . ! ' / -
            out.append(o)
        else:
            out.append(0x20)
    return bytes(out)

# Banners
with open(os.path.join(PLAYER_DIR, 'banner_top.bin'), 'wb') as f:
    f.write(to_screen("FRIET VAN DESIRE -- DEFEEST AT X2026"))
with open(os.path.join(PLAYER_DIR, 'banner_bottom.bin'), 'wb') as f:
    f.write(to_screen("KLOOT & ANUS / DEFEEST / MET MAYO"))

# Lyric table — sequence of (frame_lo, frame_hi, len, screen_bytes...)
buf = bytearray()
for frame, text in events:
    codes = to_screen(text)
    buf += bytes([frame & 0xFF, (frame >> 8) & 0xFF, len(codes)]) + codes
with open(os.path.join(PLAYER_DIR, 'lyric_table.bin'), 'wb') as f:
    f.write(buf)
print(f"Lyric table: {len(buf)} bytes")

# ---- 3. Invoke KickAssembler ------------------------------------------
if not os.path.exists(KICKASS_JAR):
    print(f"KickAss.jar not found at {KICKASS_JAR}")
    sys.exit(1)
r = subprocess.run(
    ['java', '-jar', KICKASS_JAR, ASM_PATH, '-o', OUT_PRG],
    capture_output=True, text=True,
)
print(r.stdout)
if r.returncode != 0:
    print(r.stderr)
    sys.exit(1)
size = os.path.getsize(OUT_PRG)
print(f"Wrote {OUT_PRG} ({size} bytes)")
